name: Pipeline with Jest Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Save node_modules and build
          uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            node_modules
            .next # Falls du Next.js nutzt, andernfalls den entsprechenden Build-Ordner angeben


  tests:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

